// Assemble the streamlined Fundamental course data module from the per-batch
// session JSON (condensed from the v2.0 curriculum). Exercises are terse
// Send/Copy lines; LCWO mentions are linked to the in-app LCWO guide (via the
// existing rewrite), Daily Scales stay inline, embedded practice audio links
// through. Run: node _sources/build_fundamental_data.mjs
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const LCWO = "https://cwops.org/wp-content/uploads/2025/03/LCWO-ICR-Guidelines.htm";
const sessions = (await import(pathToFileURL(resolve(here, "fundamental-sessions.js")).href)).default
  .slice()
  .sort((a, b) => a.session - b.session);
if (sessions.length !== 16) throw new Error(`Expected 16 sessions, got ${sessions.length}`);

const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function lineHtml(ex) {
  if (ex.audioUrl) {
    // Drop the generic "Copy practice file" placeholder; the linked label says it all.
    const lead = /practice file/i.test(ex.text) ? "" : esc(ex.text) + " ";
    return `<p>${ex.kind} — ${lead}<a class="audio" href="${ex.audioUrl}" target="_blank" rel="noopener">${esc(ex.audioLabel || "practice file")}</a></p>`;
  }
  let body = esc(ex.text);
  // Link the first "LCWO" mention to the in-app LCWO guide (rewriteGuideLinks
  // swaps this external URL for the guide at render time).
  if (/\bLCWO\b/.test(ex.text)) {
    body = body.replace(/\bLCWO\b/, `<a href="${LCWO}" target="_blank" rel="noopener">LCWO</a>`);
  }
  return `<p>${ex.kind} — ${body}</p>`;
}

const lessons = sessions.map((s) => {
  const wrap = s.session === 16;
  const days = s.days.map((d) => ({
    label: d.label,
    bodyHtml: d.exercises.map(lineHtml).join("\n"),
    tools: d.exercises.filter((e) => e.audioUrl).map((e) => ({ name: e.audioLabel || "Practice file", url: e.audioUrl })),
  }));
  return {
    id: s.session,
    title: wrap ? "Session 16 · Wrap-up" : `Session ${s.session} · Farnsworth ${s.speed} WPM`,
    summary: wrap
      ? "Course wrap-up — keep up the daily habit and get on the air."
      : `Sending (Daily Scales + drills) and copying (LCWO Code Groups) at Farnsworth ${s.speed} WPM.`,
    speedRange: wrap ? "Wrap-up" : `Farnsworth ${s.speed} WPM`,
    days,
  };
});

const course = {
  id: "cwops-fundamental",
  shortName: "CWA Fundamental",
  longName: "CW Academy Fundamental Curriculum (v2.0)",
  subtitle: "16 sessions · Farnsworth 6→11 WPM",
  description:
    "CW Academy's Fundamental course. Eight weeks building Instant Character Recognition and well-formed sending, from 6 to about 11 WPM Farnsworth, using the Daily Scales and LCWO.",
  source: {
    org: "CW Academy / CWops",
    author: "Roland Smith K7OJL & Bob Carter WR7Q",
    referenceUrl: "https://cwops.org/wp-content/uploads/2025/04/CW-Academy-Fundamental-Curriculum-v2.0.htm",
    filesUrl: "https://cwops.org/fundamental-practice-files/",
  },
  intro: {
    title: "About the Fundamental Course",
    sections: [
      {
        heading: "How this works",
        html:
          "<p>Each day pairs <strong>Send</strong> practice (Daily Scales warm-up, then character / word / callsign sending on your key) with <strong>Copy</strong> practice (mostly LCWO Code Groups at the day's Farnsworth speed).</p>" +
          "<p>Keep your keyer at 25 WPM character speed and slow the spacing to the session's effective speed. Record yourself now and then and listen back — clean, well-formed characters matter as much as copy.</p>",
      },
    ],
  },
  assessment: null,
  lessons,
};

const banner =
  "// Auto-generated by _sources/build_fundamental_data.mjs — do not edit by hand.\n" +
  "// Condensed from _sources/fundamental-curriculum-v2.0.htm via the per-batch _fund_s*.json.\n\n";
writeFileSync(resolve(root, "data/cwops-fundamental.js"), banner + "export default " + JSON.stringify(course, null, 2) + ";\n");

const audio = sessions.flatMap((s) => s.days).flatMap((d) => d.exercises).filter((e) => e.audioUrl).length;
console.log(`Sessions: ${lessons.length} | days: ${lessons.flatMap((l) => l.days).length} | embedded audio: ${audio}`);
console.log("Wrote data/cwops-fundamental.js");
